import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * Seed = the minimum a fresh database needs to be usable.
 *
 * Right now that is only the singleton metric_weights row. Mock accounts and
 * their 90 days of content are generated by MockProvider through the sync
 * engine (Stage 2), not hard-coded here — so that `pnpm db:reset` and
 * `pnpm sync` exercise the same code path.
 */
async function main(): Promise<void> {
  const weights = await prisma.metricWeights.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      likeWeight: 1,
      commentWeight: 3,
      shareWeight: 5,
      saveWeight: 4,
      updatedBy: "seed",
    },
  });

  console.log(
    `[seed] metric_weights ready: like=${weights.likeWeight} comment=${weights.commentWeight} share=${weights.shareWeight} save=${weights.saveWeight}`,
  );
  console.log("[seed] run `pnpm sync` to populate mock accounts and content");
}

main()
  .catch((error: unknown) => {
    console.error("[seed] failed:", error);
    process.exitCode = 1;
  })
  .finally(() => {
    void prisma.$disconnect();
  });
